services:
  app:
    build: .
    container_name: nestjs-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - nestjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 
    command: /bin/sh -c "npm run migrate && npm run start:dev"

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: air_scout
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge

volumes:
  mysql-data:
